version: "Build {build}"

environment:
  matrix:
    - PHP_VERSION: '7.1'
      PHP_ARCHITECTURE: x86

matrix:
  fast_finish: true

clone_depth: 50

cache:
  - C:\tools\downloads -> .appveyor.yml
  - C:\tools\bin -> .appveyor.yml
  - '%ProgramFiles%\WindowsPowerShell\Modules\VcRedist -> .appveyor.yml'
  - '%LOCALAPPDATA%\Composer\files'

install:
  - ps: .\.appveyor\configure.ps1
  - composer self-update      
  - composer install --no-progress --no-suggest --optimize-autoloader --no-ansi --no-interaction %PREFER_LOWEST%

build: off

test_script:
  - set APPVEYOR_SAVE_CACHE_ON_ERROR=true
  - cd /d "%APPVEYOR_BUILD_FOLDER%"
  - composer test

deploy: off
